"""Goal system — long-term goal creation, planning, tracking, and execution.

Goals can be:
- Created with a description, priority, and deadline
- Broken down into sub-goals and tasks by the LLM
- Tracked through statuses: pending → planning → in_progress → reviewing → completed/failed
- Executed step-by-step with the LLM generating and completing each step
- Linked via the knowledge graph (goals → episodes → skills)

Long-term goals support:
- Multi-step execution plans generated by the LLM
- Progress tracking with step completion
- Automatic replanning when a step fails
- Goal dependencies (one goal blocks another)
- Goal deadlines and priority scheduling
"""

from __future__ import annotations

import hashlib
import json
import logging
import os
import sqlite3
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

GOAL_STATUSES = ("pending", "planning", "in_progress", "reviewing", "completed", "failed", "paused")
GOAL_PRIORITIES = ("critical", "high", "medium", "low")


@dataclass
class Goal:
    """A long-term goal with execution plan."""
    id: str
    title: str
    description: str
    priority: str = "medium"
    status: str = "pending"
    parent_goal_id: str | None = None
    sub_goal_ids: list[str] = field(default_factory=list)
    steps: list[dict[str, Any]] = field(default_factory=list)
    current_step: int = 0
    created_at: float = 0.0
    updated_at: float = 0.0
    deadline: float | None = None
    completed_at: float | None = None
    tags: list[str] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)
    blocks_goal_ids: list[str] = field(default_factory=list)
    blocked_by_goal_ids: list[str] = field(default_factory=list)

    def as_dict(self) -> dict[str, Any]:
        return {
            "id": self.id, "title": self.title, "description": self.description,
            "priority": self.priority, "status": self.status,
            "parent_goal_id": self.parent_goal_id, "sub_goal_ids": self.sub_goal_ids,
            "steps": self.steps, "current_step": self.current_step,
            "created_at": self.created_at, "updated_at": self.updated_at,
            "deadline": self.deadline, "completed_at": self.completed_at,
            "tags": self.tags, "metadata": self.metadata,
            "blocks_goal_ids": self.blocks_goal_ids,
            "blocked_by_goal_ids": self.blocked_by_goal_ids,
            "progress": self._progress(),
        }

    def _progress(self) -> float:
        if not self.steps:
            return 0.0 if self.status != "completed" else 1.0
        completed = sum(1 for s in self.steps if s.get("status") == "completed")
        return completed / len(self.steps)


class GoalManager:
    """Manages long-term goals with planning and execution."""

    PLANNING_PROMPT = """You are a goal planning system. Given a goal, create a detailed step-by-step execution plan.

Return JSON:
{
  "steps": [
    {"title": "<step title>", "description": "<what to do>", "tool": "<tool to use if any>", "estimated_time_s": 30},
    ...
  ],
  "sub_goals": [
    {"title": "<sub-goal title>", "description": "<sub-goal description>", "priority": "medium"},
    ...
  ]
}

Break the goal into 3-8 concrete, actionable steps. Each step should be independently executable.
If the goal is complex enough to warrant sub-goals, include them. Otherwise leave sub_goals empty."""

    def __init__(self, db_path: str | Path = "~/.inc_llm/goals.db", bus: Any = None, memory: Any = None) -> None:
        self.db_path = Path(os.path.expanduser(db_path))
        self.db_path.parent.mkdir(parents=True, exist_ok=True)
        self.bus = bus
        self.memory = memory
        self._init_db()

    def _init_db(self) -> None:
        with sqlite3.connect(str(self.db_path)) as conn:
            conn.executescript("""
                CREATE TABLE IF NOT EXISTS goals (
                    id TEXT PRIMARY KEY,
                    title TEXT NOT NULL,
                    description TEXT NOT NULL,
                    priority TEXT DEFAULT 'medium',
                    status TEXT DEFAULT 'pending',
                    parent_goal_id TEXT,
                    sub_goal_ids TEXT DEFAULT '[]',
                    steps TEXT DEFAULT '[]',
                    current_step INTEGER DEFAULT 0,
                    created_at REAL NOT NULL,
                    updated_at REAL NOT NULL,
                    deadline REAL,
                    completed_at REAL,
                    tags TEXT DEFAULT '[]',
                    metadata TEXT DEFAULT '{}',
                    blocks_goal_ids TEXT DEFAULT '[]',
                    blocked_by_goal_ids TEXT DEFAULT '[]'
                );
                CREATE INDEX IF NOT EXISTS idx_goals_status ON goals(status);
                CREATE INDEX IF NOT EXISTS idx_goals_priority ON goals(priority);
                CREATE INDEX IF NOT EXISTS idx_goals_parent ON goals(parent_goal_id);
            """)

    def create_goal(self, title: str, description: str, priority: str = "medium",
                    deadline: float | None = None, parent_goal_id: str | None = None,
                    tags: list[str] | None = None, blocks: list[str] | None = None,
                    blocked_by: list[str] | None = None) -> Goal:
        """Create a new goal."""
        goal_id = hashlib.sha256(f"{title}:{time.time()}".encode()).hexdigest()[:16]
        now = time.time()
        goal = Goal(
            id=goal_id, title=title, description=description, priority=priority,
            status="pending", parent_goal_id=parent_goal_id,
            created_at=now, updated_at=now, deadline=deadline,
            tags=tags or [], blocks_goal_ids=blocks or [],
            blocked_by_goal_ids=blocked_by or [],
        )
        self._store(goal)

        if self.memory:
            self.memory.graph.add_node(
                f"goal:{goal_id}", "concept", title,
                metadata={"description": description, "priority": priority, "status": "pending"},
            )
            if parent_goal_id:
                parent = self.get_goal(parent_goal_id)
                if parent:
                    parent.sub_goal_ids.append(goal_id)
                    self._store(parent)
                    if self.memory:
                        self.memory.graph.add_edge(
                            f"goal:{parent_goal_id}", f"goal:{goal_id}", "depends_on", 0.8,
                        )

        logger.info("Created goal '%s' (%s, priority: %s)", title, goal_id, priority)
        return goal

    async def plan_goal(self, goal_id: str) -> dict[str, Any]:
        """Generate an execution plan for a goal using the LLM."""
        goal = self.get_goal(goal_id)
        if goal is None:
            return {"success": False, "message": "Goal not found"}

        if not self.bus:
            return {"success": False, "message": "No model bus available for planning"}

        goal.status = "planning"
        self._store(goal)

        try:
            prompt = f"{self.PLANNING_PROMPT}\n\nGOAL:\nTitle: {goal.title}\nDescription: {goal.description}\nPriority: {goal.priority}"
            response = await self.bus.complete(
                role="base", messages=[{"role": "user", "content": prompt}],
                max_tokens=400, temperature=0.3,
            )
            plan = self._safe_json_parse(response["content"], {"steps": [], "sub_goals": []})

            goal.steps = []
            for i, step in enumerate(plan.get("steps", [])):
                goal.steps.append({
                    "index": i, "title": step.get("title", f"Step {i+1}"),
                    "description": step.get("description", ""),
                    "tool": step.get("tool", ""), "estimated_time_s": step.get("estimated_time_s", 30),
                    "status": "pending", "result": "",
                })
            goal.current_step = 0
            goal.status = "in_progress"
            goal.updated_at = time.time()
            self._store(goal)

            for sg in plan.get("sub_goals", []):
                sub = self.create_goal(
                    title=sg.get("title", ""), description=sg.get("description", ""),
                    priority=sg.get("priority", "medium"), parent_goal_id=goal_id,
                )
                goal.sub_goal_ids.append(sub.id)
            self._store(goal)

            if self.memory:
                for step in goal.steps:
                    self.memory.graph.add_node(
                        f"goal_step:{goal_id}:{step['index']}", "concept", step["title"],
                        metadata={"description": step["description"], "status": "pending"},
                    )
                    self.memory.graph.add_edge(
                        f"goal:{goal_id}", f"goal_step:{goal_id}:{step['index']}", "depends_on", 0.8,
                    )

            logger.info("Planned goal '%s': %d steps, %d sub-goals", goal.title, len(goal.steps), len(plan.get("sub_goals", [])))
            return {"success": True, "goal": goal.as_dict(), "plan": plan}
        except Exception as e:
            goal.status = "pending"
            self._store(goal)
            logger.error("Planning failed for goal %s: %s", goal_id, e)
            return {"success": False, "message": str(e)}

    async def execute_next_step(self, goal_id: str, context: str = "") -> dict[str, Any]:
        """Execute the next step of a goal."""
        goal = self.get_goal(goal_id)
        if goal is None:
            return {"success": False, "message": "Goal not found"}
        if goal.status not in ("in_progress", "reviewing"):
            return {"success": False, "message": f"Goal is {goal.status}, not in_progress"}
        if goal.current_step >= len(goal.steps):
            goal.status = "completed"
            goal.completed_at = time.time()
            self._store(goal)
            return {"success": True, "message": "Goal completed!", "goal": goal.as_dict()}

        step = goal.steps[goal.current_step]
        step["status"] = "in_progress"
        self._store(goal)

        if self.bus:
            try:
                step_prompt = (
                    f"You are executing step {step['index']+1}/{len(goal.steps)} of a goal.\n"
                    f"Goal: {goal.title}\n"
                    f"Step: {step['title']}\n"
                    f"Description: {step['description']}\n"
                    f"Context: {context[:500]}\n"
                    f"Execute this step and provide the result. Be concise."
                )
                response = await self.bus.complete(
                    role="base", messages=[{"role": "user", "content": step_prompt}],
                    max_tokens=200, temperature=0.5,
                )
                step["result"] = response.get("content", "")
                step["status"] = "completed"
            except Exception as e:
                step["status"] = "failed"
                step["result"] = str(e)
                logger.warning("Step execution failed: %s", e)
        else:
            step["status"] = "completed"
            step["result"] = "No model bus available — marked as completed manually"

        goal.current_step += 1
        goal.updated_at = time.time()

        if goal.current_step >= len(goal.steps):
            goal.status = "completed"
            goal.completed_at = time.time()

        self._store(goal)

        if self.memory:
            self.memory.graph.add_node(
                f"goal_step:{goal_id}:{step['index']}", "concept", step["title"],
                metadata={"status": step["status"], "result": step["result"][:200]},
            )
            await self.memory.sync_after_turn(
                session_id=f"goal:{goal_id}", query=step["title"],
                result=step["result"], success=step["status"] == "completed",
            )

        logger.info("Executed step %d/%d for goal '%s': %s", goal.current_step, len(goal.steps), goal.title, step["status"])
        return {"success": True, "step": step, "goal": goal.as_dict()}

    async def execute_goal(self, goal_id: str, context: str = "") -> dict[str, Any]:
        """Execute all remaining steps of a goal sequentially."""
        goal = self.get_goal(goal_id)
        if goal is None:
            return {"success": False, "message": "Goal not found"}
        if goal.status == "pending":
            plan_result = await self.plan_goal(goal_id)
            if not plan_result["success"]:
                return plan_result
        results = []
        while True:
            step_result = await self.execute_next_step(goal_id, context)
            results.append(step_result)
            if not step_result.get("success"):
                break
            goal = self.get_goal(goal_id)
            if goal and goal.status == "completed":
                break
        return {"success": True, "results": results, "goal": self.get_goal(goal_id).as_dict() if self.get_goal(goal_id) else None}

    def get_goal(self, goal_id: str) -> Goal | None:
        with sqlite3.connect(str(self.db_path)) as conn:
            row = conn.execute("SELECT * FROM goals WHERE id = ?", (goal_id,)).fetchone()
        return self._row_to_goal(row) if row else None

    def list_goals(self, status: str | None = None, priority: str | None = None) -> list[Goal]:
        query = "SELECT * FROM goals"
        params: list[Any] = []
        conditions: list[str] = []
        if status:
            conditions.append("status = ?")
            params.append(status)
        if priority:
            conditions.append("priority = ?")
            params.append(priority)
        if conditions:
            query += " WHERE " + " AND ".join(conditions)
        query += " ORDER BY CASE priority WHEN 'critical' THEN 0 WHEN 'high' THEN 1 WHEN 'medium' THEN 2 ELSE 3 END, created_at DESC"
        with sqlite3.connect(str(self.db_path)) as conn:
            rows = conn.execute(query, params).fetchall()
        return [self._row_to_goal(r) for r in rows]

    def update_goal(self, goal_id: str, **kwargs: Any) -> Goal | None:
        goal = self.get_goal(goal_id)
        if goal is None:
            return None
        for k, v in kwargs.items():
            if hasattr(goal, k):
                setattr(goal, k, v)
        goal.updated_at = time.time()
        self._store(goal)
        return goal

    def delete_goal(self, goal_id: str) -> bool:
        with sqlite3.connect(str(self.db_path)) as conn:
            cursor = conn.execute("DELETE FROM goals WHERE id = ?", (goal_id,))
            return cursor.rowcount > 0

    def get_active_goals(self) -> list[Goal]:
        return self.list_goals(status="in_progress") + self.list_goals(status="planning")

    def get_blocked_goals(self) -> list[Goal]:
        goals = self.list_goals()
        return [g for g in goals if g.blocked_by_goal_ids and any(self.get_goal(bid) and self.get_goal(bid).status != "completed" for bid in g.blocked_by_goal_ids)]

    def get_goal_context(self) -> str:
        """Get active goals as context for the LLM."""
        active = self.get_active_goals()
        if not active:
            return ""
        lines = ["Active Goals:"]
        for g in active:
            progress = g._progress()
            lines.append(f"- [{g.priority}] {g.title} ({g.status}, {progress:.0%} done)")
            if g.current_step < len(g.steps):
                step = g.steps[g.current_step]
                lines.append(f"  Next: {step['title']}")
        return "\n".join(lines)

    def _store(self, goal: Goal) -> None:
        with sqlite3.connect(str(self.db_path)) as conn:
            conn.execute(
                """INSERT OR REPLACE INTO goals
                   (id, title, description, priority, status, parent_goal_id, sub_goal_ids,
                    steps, current_step, created_at, updated_at, deadline, completed_at,
                    tags, metadata, blocks_goal_ids, blocked_by_goal_ids)
                   VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""",
                (goal.id, goal.title, goal.description, goal.priority, goal.status,
                 goal.parent_goal_id, json.dumps(goal.sub_goal_ids), json.dumps(goal.steps),
                 goal.current_step, goal.created_at, goal.updated_at, goal.deadline,
                 goal.completed_at, json.dumps(goal.tags), json.dumps(goal.metadata),
                 json.dumps(goal.blocks_goal_ids), json.dumps(goal.blocked_by_goal_ids)),
            )

    def _row_to_goal(self, row: tuple) -> Goal:
        return Goal(
            id=row[0], title=row[1], description=row[2], priority=row[3], status=row[4],
            parent_goal_id=row[5], sub_goal_ids=json.loads(row[6]), steps=json.loads(row[7]),
            current_step=row[8], created_at=row[9], updated_at=row[10], deadline=row[11],
            completed_at=row[12], tags=json.loads(row[13]), metadata=json.loads(row[14]),
            blocks_goal_ids=json.loads(row[15]), blocked_by_goal_ids=json.loads(row[16]),
        )

    @staticmethod
    def _safe_json_parse(text: str, fallback: dict) -> dict:
        try:
            start = text.find("{")
            end = text.rfind("}") + 1
            if start >= 0 and end > start:
                return json.loads(text[start:end])
        except Exception:
            pass
        return fallback

    def count(self) -> int:
        with sqlite3.connect(str(self.db_path)) as conn:
            return conn.execute("SELECT COUNT(*) FROM goals").fetchone()[0]

    def get_stats(self) -> dict[str, int]:
        with sqlite3.connect(str(self.db_path)) as conn:
            total = conn.execute("SELECT COUNT(*) FROM goals").fetchone()[0]
            active = conn.execute("SELECT COUNT(*) FROM goals WHERE status IN ('in_progress','planning')").fetchone()[0]
            completed = conn.execute("SELECT COUNT(*) FROM goals WHERE status = 'completed'").fetchone()[0]
            failed = conn.execute("SELECT COUNT(*) FROM goals WHERE status = 'failed'").fetchone()[0]
        return {"total": total, "active": active, "completed": completed, "failed": failed}
